### ISSUE TITLE
Request

### ISSUE THREAD

**Issue by ayyneya** [cubedhuang/discord-embed-creator#2]
Hiya! 

This is a long shot but figured I'd ask.
I've been using this a lot for python projects, recently moved over to rust.

Any chance you can add an option for rust or the library Serenity (for rust)?

**Comment by cubedhuang** [comment]
yeah i just added it

i'm dubiously confident that it works though since i've never actually used serenity i just looked at the docs

try it out and tell me if it's good!

**Comment by ayyneya** [comment]
Wasn't expecting that, will test soon and let you know, thank you.
